In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
names=[]
# Assign column names to the dataset
for i in range(1,769):
 names.append("feature_"+str(i))
labels=["label_1","label_2","label_3","label_4"]
names+=labels

# Read in the dataset
train_df = pd.read_csv('DataSet_L7/train.csv')
valid_df = pd.read_csv('DataSet_L7/valid.csv')
test_df = pd.read_csv('DataSet_L7/test.csv')

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
train_df.head()

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0   0.186257  -0.058807   0.024632  -0.163933  -0.146699   0.035889   
1   0.063431  -0.023597   0.068057  -0.252915  -0.061094  -0.027316   
2   0.034962   0.035816  -0.029753  -0.094607  -0.017576  -0.053074   
3   0.033772   0.085612   0.067488  -0.073953  -0.180646  -0.024512   
4   0.134305   0.062096   0.106920  -0.089327   0.117093  -0.077107   

   feature_7  feature_8  feature_9  feature_10  ...  feature_763  feature_764  \
0   0.111708  -0.162861   0.028249   -0.098063  ...     0.055629    -0.010358   
1   0.135747  -0.168147   0.091236   -0.078473  ...    -0.014893     0.071721   
2   0.040121  -0.007932   0.097872   -0.024042  ...     0.012415     0.015215   
3   0.242879  -0.023374  -0.059999    0.002006  ...    -0.078246    -0.032903   
4   0.152579   0.047529  -0.015998   -0.110657  ...    -0.094629     0.069718   

   feature_765  feature_766  feature_767  feature_768  label_1  label_2  \
0     0.125754     0.011648     0.079197     0.093215       45      NaN   
1     0.018918     0.100032    -0.083042     0.088615       45      NaN   
2     0.083808     0.031312    -0.056277     0.064702       45      NaN   
3     0.082949    -0.020659     0.082274    -0.050164       45      NaN   
4     0.014379     0.048124     0.007586    -0.016980       45      NaN   

   label_3  label_4  
0        1        6  
1        1        6  
2        1        6  
3        1        6  
4        1        6  

[5 rows x 772 columns]

In [ ]:
train_df.shape

(28520, 772)

In [ ]:
train_df.isnull().sum()

feature_1        0
feature_2        0
feature_3        0
feature_4        0
feature_5        0
              ... 
feature_768      0
label_1          0
label_2        480
label_3          0
label_4          0
Length: 772, dtype: int64

In [ ]:
valid_df.isnull().sum()

feature_1       0
feature_2       0
feature_3       0
feature_4       0
feature_5       0
               ..
feature_768     0
label_1         0
label_2        14
label_3         0
label_4         0
Length: 772, dtype: int64

In [ ]:
test_df.isnull().sum()
test_df.head()

ID  feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0   1   0.187868  -0.009268   0.039846  -0.102515  -0.109121  -0.079769   
1   2   0.122119   0.019015   0.134483   0.007949  -0.157884  -0.033332   
2   3   0.079187   0.146195  -0.001316  -0.085596  -0.261093  -0.021620   
3   4   0.231196   0.021558   0.215534  -0.210258  -0.158189   0.041621   
4   5   0.020412   0.063732  -0.065506  -0.089598  -0.130788  -0.018809   

   feature_7  feature_8  feature_9  ...  feature_759  feature_760  \
0   0.061295  -0.042890   0.099860  ...     0.043647     0.061174   
1   0.044334  -0.016869  -0.014088  ...    -0.179798    -0.027611   
2   0.268898  -0.103950   0.068976  ...    -0.075460     0.037346   
3   0.240254  -0.068112  -0.017550  ...     0.083334     0.141642   
4   0.119304  -0.057494   0.094714  ...    -0.001969    -0.003025   

   feature_761  feature_762  feature_763  feature_764  feature_765  \
0     0.026771    -0.092734    -0.052383    -0.055526     0.029101   
1     0.240023    -0.005648    -0.057537     0.023922    -0.038126   
2     0.124254    -0.369695    -0.056773    -0.028471     0.019971   
3    -0.007219     0.031547    -0.010762    -0.169036    -0.030963   
4    -0.021156    -0.136993    -0.003615     0.036371     0.048715   

   feature_766  feature_767  feature_768  
0     0.041857    -0.027872     0.099500  
1    -0.015171    -0.006270    -0.003790  
2    -0.065683    -0.047366    -0.121744  
3     0.086698     0.114194    -0.036775  
4    -0.002688    -0.016957    -0.004331  

[5 rows x 769 columns]

In [3]:
from sklearn.preprocessing import RobustScaler

x_train ={}
y_train ={}
x_valid ={}
y_valid ={}
x_test = {}

df_t = train_df
df_v = valid_df

for label in labels:
  scaler = RobustScaler()
  if label == 'label_2':
    df_t = train_df.dropna()
    df_v = valid_df.dropna()

  x_train[label] = scaler.fit_transform(df_t.drop(labels, axis=1))
  y_train[label] = df_t[label]
  x_valid[label] = scaler.transform(df_v.drop(labels, axis=1))
  y_valid[label] = df_v[label]
  x_test[label] = scaler.transform(test_df.drop(['ID'], axis=1))




In [ ]:
pd.DataFrame(x_train['label_2']).shape

(28040, 768)

#Label 1

##KNN

In [4]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train['label_2'], y_train['label_2'])

KNeighborsClassifier()

In [5]:
y_pred = classifier.predict(x_valid['label_2'])

In [6]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_2'], y_pred))
print(classification_report(y_valid['label_2'], y_pred))

[[ 29   1   1   0   4   0   0   1   0   0   0   0   0   0   0   0   0]
 [  4  60   1   0   4   1   0   0   0   0   0   0   0   0   0   1   0]
 [  1   2  39   1   1   0   0   0   0   1   0   1   0   0   0   0   0]
 [  1   1   1  65   5   3   0   0   1   1   0   0   0   0   1   0   0]
 [  0   1   1   1 108   1   1   1   0   0   1   0   0   0   0   0   0]
 [  2   4   1   0   1  70   0   2   1   0   0   0   0   0   0   0   0]
 [  0   0   0   0   2   2  41   0   0   0   0   0   0   0   1   0   0]
 [  0   1   0   0   2   2   0  40   0   0   0   0   0   0   0   0   0]
 [  0   2   0   2   3   0   2   0  37   1   0   1   0   0   0   0   0]
 [  2   0   1   1   3   0   0   0   0  58   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0  10   0   0   0   0   0   0]
 [  0   0   1   0   2   0   0   0   0   0   0  27   0   0   0   0   0]
 [  0   0   0   0   1   0   1   0   0   0   0   0   9   0   0   0   0]
 [  0   0   0   0   2   0   0   0   0   0   0   0   0   9   0   0   0]
 [  0 

#KNN with tuning 

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

param_grid = {
    'n_neighbors': [1, 2,3,4, 5, 6,7,8, 9,10]  # You can adjust this range as needed
}

knn = KNeighborsClassifier()
grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')

grid_search.fit(x_train['label_2'], y_train['label_2'])
best_k = grid_search.best_params_['n_neighbors']

final_classifier = KNeighborsClassifier(n_neighbors=best_k)
final_classifier.fit(x_train['label_2'], y_train['label_2'])

y_pred = final_classifier.predict(x_valid['label_2'])

print('Best k:',best_k)
print(confusion_matrix(y_valid['label_2'], y_pred))
print(classification_report(y_valid['label_2'], y_pred))


Best k: 1
[[ 31   0   2   0   2   0   0   1   0   0   0   0   0   0   0   0   0]
 [  3  61   0   1   6   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   2  39   0   1   1   0   1   0   0   0   1   0   0   0   0   0]
 [  1   0   1  67   5   1   2   0   0   2   0   0   0   0   0   0   0]
 [  0   1   1   2 110   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2   1   0   0  73   3   1   1   0   0   0   0   0   0   0   0]
 [  0   0   1   1   2   2  37   1   0   1   0   0   0   0   1   0   0]
 [  0   2   0   0   0   2   0  41   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   4   0   3   0  38   0   0   1   0   0   0   0   1]
 [  1   0   1   1   2   0   0   0   0  58   2   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  11   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0   0   1   0   0  28   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0  10   0   0   0   0]
 [  0   0   0   0   1   0   0   0   0   0   0   0   0  10   0   0  

#PCA+ KNN tuning 

In [30]:
from sklearn.decomposition import PCA

# Instantiate PCA with a desired number of components (e.g., n_components=50)
pca = PCA(n_components=400)

# Fit PCA on your training data
x_train_pca = pca.fit_transform(x_train['label_2'])

# Transform your validation and test data using the same PCA model
x_valid_pca = pca.transform(x_valid['label_2'])
x_test_pca = pca.transform(x_test['label_2'])  # If you have a test set

# Now, you can use x_train_pca, x_valid_pca, and x_test_pca as your reduced-dimensional feature vectors for modeling.
x_train_pca.shape

(28040, 400)

In [31]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

param_grid = {
    'leaf_size' : list(range(1,50)),
    'n_neighbors' :list(range(1,30)),
    # 'n_neighbors': [1, 2,3,4, 5, 6,7,8, 9,10],  # You can adjust this range as needed
    'p': [1, 2]
}

knn = KNeighborsClassifier()
grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')

grid_search.fit(x_train_pca, y_train['label_2'])
best_k = grid_search.best_params_['n_neighbors','leaf_size', 'p']

final_classifier = KNeighborsClassifier(n_neighbors=best_k)
final_classifier.fit(x_train_pca, y_train['label_2'])

y_pred = final_classifier.predict(x_valid_pca)

print('Best k:',best_k)
print(confusion_matrix(y_valid['label_2'], y_pred))
print(classification_report(y_valid['label_2'], y_pred))

Best k: 1
[[ 30   0   2   0   3   0   0   1   0   0   0   0   0   0   0   0   0]
 [  3  61   0   1   5   1   0   0   0   0   0   0   0   0   0   0   0]
 [  1   2  39   0   1   1   0   1   0   0   0   1   0   0   0   0   0]
 [  1   1   1  67   5   1   1   0   0   2   0   0   0   0   0   0   0]
 [  0   1   1   2 110   1   0   0   0   0   0   0   0   0   0   0   0]
 [  1   2   1   0   1  71   3   1   1   0   0   0   0   0   0   0   0]
 [  0   0   1   1   2   2  37   1   0   1   0   0   0   0   1   0   0]
 [  1   2   0   0   0   1   0  41   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   3   0   3   0  39   0   0   1   0   0   0   0   1]
 [  1   0   2   1   2   0   0   0   0  58   1   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  11   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0   0   1   0   0  28   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0  10   0   0   0   0]
 [  0   0   0   0   2   0   0   0   0   0   0   0   0   9   0   0  

In [32]:
print('Best leaf_size:', grid_search.best_estimator_.get_params()['leaf_size'])
print('Best p:', grid_search.best_estimator_.get_params()['p'])
print('Best n_neighbors:', grid_search.best_estimator_.get_params()['n_neighbors'])

Best leaf_size: 30
Best p: 1
Best n_neighbors: 1


#Label 1 PCA+ knn tuning

In [19]:
from sklearn.decomposition import PCA

# Instantiate PCA with a desired number of components (e.g., n_components=50)
pca = PCA(n_components=400)

# Fit PCA on your training data
x_train_pca = pca.fit_transform(x_train['label_1'])

# Transform your validation and test data using the same PCA model
x_valid_pca = pca.transform(x_valid['label_1'])
x_test_pca = pca.transform(x_test['label_1'])  # If you have a test set

# Now, you can use x_train_pca, x_valid_pca, and x_test_pca as your reduced-dimensional feature vectors for modeling.
x_train_pca.shape

(28520, 400)

In [28]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

param_grid = {
    'n_neighbors': [1, 2,3,4, 5, 6,7,8, 9,10],
    'p': [1, 2] 
}

knn = KNeighborsClassifier()
grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')

grid_search.fit(x_train_pca, y_train['label_1'])
best_k = grid_search.best_params_['n_neighbors']

final_classifier = KNeighborsClassifier(n_neighbors=best_k)
final_classifier.fit(x_train_pca, y_train['label_1'])

y_pred = final_classifier.predict(x_valid_pca)

print('Best k:',best_k)
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

KeyboardInterrupt: 

##SVM

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import classification_report
from scipy.stats import uniform, randint

In [ ]:
from sklearn.decomposition import PCA

# Instantiate PCA with a desired number of components (e.g., n_components=50)
pca = PCA(n_components=350)

# Fit PCA on your training data
x_train_pca = pca.fit_transform(x_train['label_2'])

# Transform your validation and test data using the same PCA model
x_valid_pca = pca.transform(x_valid['label_2'])
x_test_pca = pca.transform(x_test['label_2'])  # If you have a test set

# Now, you can use x_train_pca, x_valid_pca, and x_test_pca as your reduced-dimensional feature vectors for modeling.
x_train_pca.shape

(28520, 400)

In [ ]:
pd.DataFrame(x_train_pca)

0          1         2         3          4          5    \
0      14.141137   1.757399 -6.011598 -1.549809  -5.533205   3.069755   
1      -0.055825   7.098817  2.441451  6.707103   4.784069  -3.199298   
2      -4.181035  11.751734 -5.137172  0.876813  -4.564641   0.979505   
3      -1.618872  -0.421247  6.360317  0.293023  -1.193303  -4.980271   
4       2.740203   1.552950 -2.641521  5.782143  10.572141   1.117830   
...          ...        ...       ...       ...        ...        ...   
28515  -5.651805  13.804510 -3.727424 -0.470373  -9.544083   1.284753   
28516   0.656379   0.127061 -6.609875 -7.931759   4.223875  -3.498405   
28517  -7.730342   2.395539  3.669455 -3.432518   1.333108   9.413259   
28518  12.988838  -0.759326 -5.440311 -1.970844  -3.861694   5.732011   
28519  -8.782643  -2.284326  7.465380 -4.576645   4.237393  13.150277   

            6         7         8         9    ...       390       391  \
0     -1.930802  2.005719  0.429892  6.139024  ...  0.193010 -0.492481   
1      1.051284  0.670880 -2.809372  1.371238  ... -0.053823  0.081717   
2      2.597162 -0.002129  0.177368 -2.895701  ... -0.096682 -0.186332   
3      1.333557  7.554658  4.333935  1.598901  ... -0.399560 -0.210579   
4      4.666824 -1.300311  6.340427 -3.190307  ... -0.194258  0.158061   
...         ...       ...       ...       ...  ...       ...       ...   
28515  3.092439 -0.683669 -1.009392 -1.890243  ...  0.016002  0.213209   
28516 -0.578157  2.649631 -3.184036 -4.518412  ... -0.267557  0.198904   
28517 -2.096879  1.174211 -0.654335  1.907130  ...  0.011813  0.526027   
28518 -2.475813  1.967593  0.976162  2.886242  ...  0.083468 -0.060319   
28519 -4.046251  0.936129 -0.324825  5.157357  ... -0.295741  0.336376   

            392       393       394       395       396       397       398  \
0     -0.073585  0.365000  0.035715  0.018748  0.013538  0.030854 -0.135038   
1      0.594274  0.086277 -0.355933  0.562878 -0.079062  0.016058  0.818525   
2     -0.076901 -0.164443  0.120631 -0.303517  0.104136  0.106510 -0.035545   
3     -0.116511  0.107600 -0.010901 -0.690007 -0.005226  0.162164  0.016159   
4     -0.390869 -0.304014 -0.082834  0.104290  0.271381 -0.098731 -0.493513   
...         ...       ...       ...       ...       ...       ...       ...   
28515  0.020319  0.036019  0.026550  0.337825 -0.203154  0.292060 -0.077269   
28516 -0.125069  0.204384  0.340939 -0.144584  0.261425 -0.115345  0.000215   
28517 -0.251539  0.244195  0.155801  0.004485  0.174467  0.004056 -0.110188   
28518 -0.272793  0.278703 -0.117891  0.266656  0.060700  0.112991 -0.045264   
28519 -0.285136  0.264267  0.147735  0.102831  0.586321 -0.222413 -0.363381   

            399  
0     -0.412747  
1      0.022031  
2      0.164923  
3      0.525058  
4     -0.065833  
...         ...  
28515 -0.149470  
28516 -0.188724  
28517  0.133053  
28518  0.477330  
28519  0.175727  

[28520 rows x 400 columns]

In [ ]:
svm_classifier = SVC(class_weight='balanced', kernel='linear')
svm_classifier.fit(x_train['label_2'], y_train['label_2'])

# Make predictions on the test data
y_pred = svm_classifier.predict(x_valid['label_2'])

# Evaluate model performance
print(classification_report(y_valid['label_2'], y_pred))

              precision    recall  f1-score   support

        22.0       0.74      0.89      0.81        36
        23.0       0.65      0.77      0.71        71
        24.0       0.76      0.83      0.79        46
        25.0       0.80      0.82      0.81        79
        26.0       0.87      0.79      0.83       115
        27.0       0.83      0.78      0.80        81
        28.0       0.80      0.87      0.83        46
        29.0       0.97      0.82      0.89        45
        30.0       0.84      0.77      0.80        48
        31.0       0.84      0.80      0.82        65
        32.0       0.85      1.00      0.92        11
        33.0       0.94      0.97      0.95        30
        34.0       1.00      0.91      0.95        11
        35.0       1.00      0.82      0.90        11
        36.0       0.89      1.00      0.94         8
        41.0       1.00      0.93      0.96        14
        61.0       1.00      0.95      0.97        19

    accuracy              

In [ ]:
# Define the hyperparameter grid
param_grid = {
    'C': [0.01, 0.1, 1,10,100],  # Adjust the range
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],  # Experiment with different kernels
    'class_weight': ['balanced',None],  # Change class_weight options
    'gamma':['scale', 'auto'],
    'degree': [1,2,3,4]

}

# Create an SVM classifier
svm_classifier = SVC()

# Perform grid search with cross-validation
grid_search = GridSearchCV(svm_classifier, param_grid, scoring='accuracy', cv=5,n_jobs=-1)
grid_search.fit(x_train_pca, y_train['label_1'])

# Get the best model and hyperparameters
best_svm_classifier = grid_search.best_estimator_
best_params = grid_search.best_params_

# Make predictions on the validation set
y_pred = best_svm_classifier.predict(x_valid_pca)

# Evaluate the model
print("Best Hyperparameters:", best_params)
print("Classification Report on Validation Data:")
print(classification_report(y_valid['label_1'], y_pred))

KeyboardInterrupt: 

In [ ]:
param_distributions = {
    'C': [0.001,0.1,1,10,100],#uniform(0.001,100),  # Continuous uniform distribution for 'C'
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],  # Experiment with different kernels
    'class_weight': ['balanced', None],  # Change class_weight options
    'gamma':['scale', 'auto'],
    'degree': [1,2,3,4]
}

# Create an SVM classifier
svm_classifier = SVC()

# Example with Randomized Search
random_search = RandomizedSearchCV(svm_classifier, param_distributions, n_iter=10, cv=5, scoring='accuracy', random_state=42)
random_search.fit(x_train_pca, y_train['label_2'])

# Get the best hyperparameters and model
best_svm_classifier = random_search.best_estimator_
best_params = random_search.best_params_

# Make predictions on the validation data
y_pred = best_svm_classifier.predict(x_valid_pca)

# Evaluate the model
print("Best Hyperparameters:", best_params)
print("Classification Report on Validation Data:")
print(classification_report(y_valid['label_2'], y_pred))

In [ ]:
label_4_pred_before = svm_classifier.predict(x_test['label_2'])

##SVC with cuML

In [ ]:
# Import cuML's SVM classifier
from cuml import SVC
from sklearn.metrics import classification_report

# Instantiate cuML's PCA with the desired number of components
from cuml.decomposition import PCA
pca = PCA(n_components=400)

# Fit PCA on your training data
x_train_pca = pca.fit_transform(x_train['label_1'])

# Transform your validation and test data using the same PCA model
x_valid_pca = pca.transform(x_valid['label_1'])
x_test_pca = pca.transform(x_test['label_1'])  # If you have a test set

# Now, you can use x_train_pca, x_valid_pca, and x_test_pca as your reduced-dimensional feature vectors for modeling.
x_train_pca.shape


(28520, 400)

In [ ]:
# Instantiate cuML's SVM classifier
svm_classifier = SVC(class_weight='balanced', C=1, degree=2, gamma='scale', kernel='rbf')

# Fit the cuML SVM classifier on your training data
svm_classifier.fit(x_train_pca, y_train['label_1'])

# Make predictions on the test data
y_pred = svm_classifier.predict(x_valid_pca)

# Evaluate model performance using cuML's classification report
print(classification_report(y_valid['label_1'], y_pred))

MemoryError: ignored

In [ ]:
# Import cuML's SVM classifier and RandomizedSearchCV
from cuml import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from scipy.stats import uniform, randint

In [ ]:
# Define the hyperparameter grid
param_grid = {
    'C': [0.01, 0.1, 1,10,100],  # Adjust the range
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],  # Experiment with different kernels
    'class_weight': ['balanced',None],  # Change class_weight options
    'gamma':['scale', 'auto'],
    'degree': [1,2,3,4]

}

# Create an SVM classifier
svm_classifier = SVC()

# Perform grid search with cross-validation
grid_search = GridSearchCV(svm_classifier, param_grid, scoring='accuracy', cv=5,n_jobs=-1)
grid_search.fit(x_train_pca, y_train['label_1'])

# Get the best model and hyperparameters
best_svm_classifier = grid_search.best_estimator_
best_params = grid_search.best_params_

# Make predictions on the validation set
y_pred = best_svm_classifier.predict(x_valid_pca)

# Evaluate the model
print("Best Hyperparameters:", best_params)
print("Classification Report on Validation Data:")
print(classification_report(y_valid['label_1'], y_pred))

KeyboardInterrupt: ignored

##Random Forest

In [ ]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier  # You can replace this with any other model


In [ ]:
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train['label_2'], y_train['label_2'])  # Assuming x_train and y_train are your feature and target data


RandomForestClassifier()

In [ ]:
# Make predictions on the test data
y_pred = model.predict(x_valid['label_2'])

# Evaluate model performance
print(classification_report(y_valid['label_2'], y_pred))

              precision    recall  f1-score   support

        22.0       1.00      0.56      0.71        36
        23.0       0.84      0.75      0.79        71
        24.0       0.88      0.78      0.83        46
        25.0       0.78      0.73      0.76        79
        26.0       0.55      0.96      0.70       115
        27.0       0.86      0.88      0.87        81
        28.0       0.83      0.74      0.78        46
        29.0       1.00      0.73      0.85        45
        30.0       0.95      0.77      0.85        48
        31.0       0.88      0.80      0.84        65
        32.0       1.00      0.73      0.84        11
        33.0       1.00      0.80      0.89        30
        34.0       1.00      0.82      0.90        11
        35.0       1.00      0.82      0.90        11
        36.0       1.00      1.00      1.00         8
        41.0       1.00      0.71      0.83        14
        61.0       1.00      0.79      0.88        19

    accuracy              

##XGBoost

In [ ]:
pip install xgboost

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# Initialize the XGBoost classifier
model = xgb.XGBClassifier()
y_train_shifted = y_train['label_1'] - 1

# Train the model
model.fit(x_train['label_1'],y_train_shifted )




KeyboardInterrupt: ignored

In [ ]:
y_pred = model.predict(x_valid['label_1'])

accuracy = accuracy_score(y_valid['label_1'], y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Additional evaluation metrics
print(classification_report(y_valid['label_1'], y_pred))


##Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report


In [ ]:
# Initialize the Decision Tree classifier
model = DecisionTreeClassifier(random_state=42)

# Train the model
model.fit(x_train['label_1'], y_train['label_1'])


DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred = model.predict(x_valid['label_1'])


In [ ]:
accuracy = accuracy_score(y_valid['label_1'], y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Additional evaluation metrics
print(classification_report(y_valid['label_1'], y_pred))


Accuracy: 0.37
              precision    recall  f1-score   support

           1       0.27      0.31      0.29        13
           2       0.33      0.44      0.38         9
           3       0.40      0.33      0.36        12
           4       0.38      0.38      0.38        16
           5       0.42      0.28      0.33        18
           6       0.27      0.33      0.30         9
           7       0.50      0.35      0.41        17
           8       0.33      0.29      0.31        14
           9       0.55      0.55      0.55        11
          10       0.71      0.62      0.67         8
          11       0.69      0.47      0.56        19
          12       0.67      0.86      0.75         7
          13       0.19      0.27      0.22        11
          14       0.40      0.40      0.40        15
          15       0.45      0.53      0.49        17
          16       0.30      0.21      0.25        14
          17       0.62      0.57      0.59        14
          18