In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
names=[]
# Assign column names to the dataset
for i in range(1,769):
 names.append("feature_"+str(i))
labels=["label_1","label_2","label_3","label_4"]
names+=labels

# Read in the dataset
train_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mini_project/DataSet_L7/train.csv')
valid_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mini_project/DataSet_L7/valid.csv')
test_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mini_project/DataSet_L7/test.csv')

In [ ]:
train_df.shape

(28520, 772)

In [ ]:
train_df.isnull().sum()

feature_1        0
feature_2        0
feature_3        0
feature_4        0
feature_5        0
              ... 
feature_768      0
label_1          0
label_2        480
label_3          0
label_4          0
Length: 772, dtype: int64

In [ ]:
valid_df.isnull().sum()

feature_1       0
feature_2       0
feature_3       0
feature_4       0
feature_5       0
               ..
feature_768     0
label_1         0
label_2        14
label_3         0
label_4         0
Length: 772, dtype: int64

In [ ]:
test_df.isnull().sum()
test_df.head()

ID  feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0   1   0.187868  -0.009268   0.039846  -0.102515  -0.109121  -0.079769   
1   2   0.122119   0.019015   0.134483   0.007949  -0.157884  -0.033332   
2   3   0.079187   0.146195  -0.001316  -0.085596  -0.261093  -0.021620   
3   4   0.231196   0.021558   0.215534  -0.210258  -0.158189   0.041621   
4   5   0.020412   0.063732  -0.065506  -0.089598  -0.130788  -0.018809   

   feature_7  feature_8  feature_9  ...  feature_759  feature_760  \
0   0.061295  -0.042890   0.099860  ...     0.043647     0.061174   
1   0.044334  -0.016869  -0.014088  ...    -0.179798    -0.027611   
2   0.268898  -0.103950   0.068976  ...    -0.075460     0.037346   
3   0.240254  -0.068112  -0.017550  ...     0.083334     0.141642   
4   0.119304  -0.057494   0.094714  ...    -0.001969    -0.003025   

   feature_761  feature_762  feature_763  feature_764  feature_765  \
0     0.026771    -0.092734    -0.052383    -0.055526     0.029101   
1     0.240023    -0.005648    -0.057537     0.023922    -0.038126   
2     0.124254    -0.369695    -0.056773    -0.028471     0.019971   
3    -0.007219     0.031547    -0.010762    -0.169036    -0.030963   
4    -0.021156    -0.136993    -0.003615     0.036371     0.048715   

   feature_766  feature_767  feature_768  
0     0.041857    -0.027872     0.099500  
1    -0.015171    -0.006270    -0.003790  
2    -0.065683    -0.047366    -0.121744  
3     0.086698     0.114194    -0.036775  
4    -0.002688    -0.016957    -0.004331  

[5 rows x 769 columns]

In [ ]:
from sklearn.preprocessing import RobustScaler

x_train ={}
y_train ={}
x_valid ={}
y_valid ={}
x_test = {}

df_t = train_df
df_v = valid_df

for label in labels:
  scaler = RobustScaler()
  if label == 'label_2':
    df_t = train_df.dropna()
    df_v = valid_df.dropna()

  x_train[label] = scaler.fit_transform(df_t.drop(labels, axis=1))
  y_train[label] = df_t[label]
  x_valid[label] = scaler.transform(df_v.drop(labels, axis=1))
  y_valid[label] = df_v[label]
  x_test[label] = scaler.transform(test_df.drop(['ID'], axis=1))




#Label 1

##PCA

In [ ]:
from sklearn.decomposition import PCA

# Instantiate PCA with a desired number of components (e.g., n_components=50)
pca = PCA(n_components=0.97)

# Fit PCA on your training data
x_train_pca = pca.fit_transform(x_train['label_1'])

# Transform your validation and test data using the same PCA model
x_valid_pca = pca.transform(x_valid['label_1'])
x_test_pca = pca.transform(x_test['label_1'])  # If you have a test set

# Now, you can use x_train_pca, x_valid_pca, and x_test_pca as your reduced-dimensional feature vectors for modeling.
x_train_pca.shape

(28520, 411)

##KNN

###Original


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train['label_1'], y_train['label_1'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_valid['label_1'])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

[[11  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 11 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  1  0  7]]
              precision    recall  f1-score   support

           1       0.92      0.85      0.88        13
           2       0.82      1.00      0.90         9
           3       0.69      0.92      0.79        12
           4       0.71      0.94      0.81        16
           5       0.83      0.83      0.83        18
           6       0.88      0.78      0.82         9
           7       0.76      0.94      0.84        17
           8       0.92      0.79      0.85        14
           9       0.91      0.91      0.91        11
          10       0.80      1.00      0.89         8
          11       0.78      0.95      0.86        19
          12       0.78      1.00      0.88         7
          13       0.77      0.91      0.83        11
          14       1.00      0.87      0.93        15
          15       0.94      0.94

###After PCA

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train_pca, y_train['label_1'])

y_pred = classifier.predict(x_valid_pca)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

[[11  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 11 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  1  0  7]]
              precision    recall  f1-score   support

           1       0.92      0.85      0.88        13
           2       0.82      1.00      0.90         9
           3       0.69      0.92      0.79        12
           4       0.68      0.94      0.79        16
           5       0.75      0.83      0.79        18
           6       0.88      0.78      0.82         9
           7       0.76      0.94      0.84        17
           8       0.92      0.79      0.85        14
           9       0.91      0.91      0.91        11
          10       0.80      1.00      0.89         8
          11       0.78      0.95      0.86        19
          12       0.70      1.00      0.82         7
          13       0.77      0.91      0.83        11
          14       0.92      0.80      0.86        15
          15       0.94      0.94

###After PCA + HP tuning

##SVM

###Original

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import classification_report, accuracy_score
from scipy.stats import uniform, randint

In [ ]:
svm_classifier = SVC(class_weight='balanced' ,C=1, kernel='rbf')
svm_classifier.fit(x_train['label_1'], y_train['label_1'])

# Make predictions on the test data
y_pred = svm_classifier.predict(x_valid['label_1'])

# Evaluate model performance
print(accuracy_score(y_valid['label_1'], y_pred))

0.956


###After PCA

In [9]:
svm_classifier = SVC(class_weight='balanced' ,C=1, kernel='rbf')
svm_classifier.fit(x_train_pca, y_train['label_1'])

# Make predictions on the test data
y_pred = svm_classifier.predict(x_valid_pca)

# Evaluate model performance
print(accuracy_score(y_valid['label_1'], y_pred))

0.9573333333333334


###After PCA + HP tuning

In [ ]:
# svm_classifier = SVC(class_weight='balanced' ,C=10, degree=1, gamma='auto', kernel='poly') #=0.97
svm_classifier = SVC(class_weight='balanced' ,C=100, degree=3,  kernel='rbf') #0.98
svm_classifier.fit(x_train_pca, y_train['label_1'])

# Make predictions on the test data
y_pred = svm_classifier.predict(x_valid_pca)

# Evaluate model performance
print(classification_report(y_valid['label_1'], y_pred))

              precision    recall  f1-score   support

           1       0.93      1.00      0.96        13
           2       1.00      1.00      1.00         9
           3       0.92      1.00      0.96        12
           4       0.89      1.00      0.94        16
           5       1.00      1.00      1.00        18
           6       1.00      1.00      1.00         9
           7       1.00      0.94      0.97        17
           8       1.00      1.00      1.00        14
           9       1.00      0.91      0.95        11
          10       1.00      1.00      1.00         8
          11       1.00      1.00      1.00        19
          12       1.00      1.00      1.00         7
          13       1.00      0.91      0.95        11
          14       0.94      1.00      0.97        15
          15       1.00      0.94      0.97        17
          16       1.00      1.00      1.00        14
          17       1.00      1.00      1.00        14
          18       1.00    

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score, StratifiedKFold

# Define the cross-validation strategy (e.g., StratifiedKFold with 5 folds)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Define your SVM classifier with the desired hyperparameters
svm_classifier = SVC(class_weight='balanced' ,C=10, degree=1, gamma='auto', kernel='poly') #=0.97 -> 0.95
# svm_classifier = SVC(class_weight='balanced' ,C=100, degree=3,  kernel='rbf') #0.98 -> 0.96

# Perform cross-validation and calculate accuracy scores
scores = cross_val_score(svm_classifier, x_train_pca, y_train['label_1'], cv=cv, scoring='accuracy')

# Print the cross-validation scores and mean accuracy
print("Cross-validation scores:", scores)
print("Mean accuracy:", scores.mean())

Cross-validation scores: [0.94652875 0.95038569 0.95319074 0.95126227 0.94968443]
Mean accuracy: 0.9502103786816269


In [ ]:
# Define the hyperparameter grid
param_grid = {
    'C': [0.01, 0.1, 1,10,100],  # Adjust the range
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],  # Experiment with different kernels
    'class_weight': ['balanced',None],  # Change class_weight options
    'gamma':['scale', 'auto'],
    'degree': [1,2,3,4]

}

# Create an SVM classifier
svm_classifier = SVC()

# Perform grid search with cross-validation
grid_search = GridSearchCV(svm_classifier, param_grid, scoring='accuracy', cv=5,n_jobs=-1)
grid_search.fit(x_train_pca, y_train['label_1'])

# Get the best model and hyperparameters
best_svm_classifier = grid_search.best_estimator_
best_params = grid_search.best_params_

# Make predictions on the validation set
y_pred = best_svm_classifier.predict(x_valid_pca)

# Evaluate the model
print("Best Hyperparameters:", best_params)
print("Classification Report on Validation Data:")
print(classification_report(y_valid['label_1'], y_pred))

In [ ]:
param_distributions = {
    'C': [0.001,0.1,1,10,100],#uniform(0.001,100),  # Continuous uniform distribution for 'C'
    'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],  # Experiment with different kernels
    # 'class_weight': ['balanced', None],  # Change class_weight options
    # 'gamma':['scale', 'auto'],
    'degree': [1,2,3,4]
}

# Create an SVM classifier
svm_classifier = SVC()

# Example with Randomized Search
random_search = RandomizedSearchCV(svm_classifier, param_distributions, n_iter=20, cv=5, scoring='accuracy', random_state=42)
random_search.fit(x_train_pca, y_train['label_1'])

# Get the best hyperparameters and model
best_svm_classifier = random_search.best_estimator_
best_params = random_search.best_params_

# Make predictions on the validation data
y_pred = best_svm_classifier.predict(x_valid_pca)

# Evaluate the model
print("Best Hyperparameters:", best_params)
print("Classification Report on Validation Data:")
print(classification_report(y_valid['label_1'], y_pred))

Best Hyperparameters: {'kernel': 'rbf', 'degree': 3, 'C': 100}
Classification Report on Validation Data:
              precision    recall  f1-score   support

           1       0.93      1.00      0.96        13
           2       1.00      1.00      1.00         9
           3       0.92      1.00      0.96        12
           4       0.89      1.00      0.94        16
           5       1.00      1.00      1.00        18
           6       1.00      1.00      1.00         9
           7       1.00      0.94      0.97        17
           8       1.00      1.00      1.00        14
           9       1.00      0.91      0.95        11
          10       1.00      1.00      1.00         8
          11       1.00      1.00      1.00        19
          12       1.00      1.00      1.00         7
          13       1.00      0.91      0.95        11
          14       0.94      1.00      0.97        15
          15       1.00      0.94      0.97        17
          16       1.00      1

In [ ]:
label_1_pred = svm_classifier.predict(x_test_pca)

##Random Forest

###Orginal

In [ ]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier  # You can replace this with any other model


In [ ]:
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train['label_1'], y_train['label_1'])  # Assuming x_train and y_train are your feature and target data


RandomForestClassifier()

In [ ]:
# Make predictions on the test data
y_pred = model.predict(x_valid['label_1'])

# Evaluate model performance
print(classification_report(y_valid['label_1'], y_pred))

              precision    recall  f1-score   support

           1       0.83      0.77      0.80        13
           2       0.89      0.89      0.89         9
           3       0.79      0.92      0.85        12
           4       0.89      1.00      0.94        16
           5       0.89      0.89      0.89        18
           6       0.90      1.00      0.95         9
           7       0.84      0.94      0.89        17
           8       1.00      0.79      0.88        14
           9       0.90      0.82      0.86        11
          10       0.89      1.00      0.94         8
          11       0.90      0.95      0.92        19
          12       0.88      1.00      0.93         7
          13       0.91      0.91      0.91        11
          14       0.88      0.93      0.90        15
          15       0.89      0.94      0.91        17
          16       0.87      0.93      0.90        14
          17       0.87      0.93      0.90        14
          18       0.92    

###After PCA

###After PCA + HP tuning

##XGBoost

In [ ]:
pip install xgboost

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# Initialize the XGBoost classifier
model = xgb.XGBClassifier()
y_train_shifted = y_train['label_1'] - 1

# Train the model
model.fit(x_train['label_1'],y_train_shifted )




KeyboardInterrupt: ignored

In [ ]:
y_pred = model.predict(x_valid['label_1'])

accuracy = accuracy_score(y_valid['label_1'], y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Additional evaluation metrics
print(classification_report(y_valid['label_1'], y_pred))


##Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report


In [ ]:
# Initialize the Decision Tree classifier
model = DecisionTreeClassifier(random_state=42)

# Train the model
model.fit(x_train['label_1'], y_train['label_1'])


DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred = model.predict(x_valid['label_1'])


In [ ]:
accuracy = accuracy_score(y_valid['label_1'], y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Additional evaluation metrics
print(classification_report(y_valid['label_1'], y_pred))


Accuracy: 0.37
              precision    recall  f1-score   support

           1       0.27      0.31      0.29        13
           2       0.33      0.44      0.38         9
           3       0.40      0.33      0.36        12
           4       0.38      0.38      0.38        16
           5       0.42      0.28      0.33        18
           6       0.27      0.33      0.30         9
           7       0.50      0.35      0.41        17
           8       0.33      0.29      0.31        14
           9       0.55      0.55      0.55        11
          10       0.71      0.62      0.67         8
          11       0.69      0.47      0.56        19
          12       0.67      0.86      0.75         7
          13       0.19      0.27      0.22        11
          14       0.40      0.40      0.40        15
          15       0.45      0.53      0.49        17
          16       0.30      0.21      0.25        14
          17       0.62      0.57      0.59        14
          18